version: "3.7"
services: 
  postgres:
    image: postgres
    container_name: pgdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - todonw
    volumes:
      - ./env/pg/:/docker-entrypoint-initdb.d/
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    networks:
      - todonw
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  todonw:
      name: todonw